### PR TITLE
Upgrade all possible dependencies

### PR DESCRIPTION
**Pull request by nathanchapman**
- Upgrade + pin all dependencies
- Improve build commands

https://capacitorjs.com/docs/updating/5-0
https://nextjs.org/docs/app/building-your-application/upgrading/version-14#upgrading-from-13-to-14

Addresses #54, #41, and #43

Note: I was unable to upgrade `react-router` and `react-router-dom` from 5.x to 6.x at this time due to the peer dependency requirements of `^5.x` from `@ionic/react-router`

### CODE REVIEW

**Comment by mlynch** [comment]
Do you guys have permission to merge/update? If so let me know what I have to do to enable that. I won't be able to review contributions but trust you guys know what's best anyways

**Comment by nathanchapman** [comment]
@mlynch yes, I do! I was waiting on review just as a general best practice, but will go ahead and merge this one in. Thanks!

**Comment by CharlesOnAir** [comment]
Still a few dependencies out of date. Unfortunately, some of them require major updates.

CleanShot 2024-02-27 at 17 36 43@2x

**Comment by nathanchapman** [comment]
> Still a few dependencies out of date. Unfortunately, some of them require major updates. How we can fix that ? We can't because of ion-router?
> 
> CleanShot 2024-02-27 at 17 36 43@2x

correct

> Note: I was unable to upgrade react-router and react-router-dom from 5.x to 6.x at this time due to the peer dependency requirements of ^5.x from @ionic/react-router

**Pull request merged**
